### ISSUE TITLE
MunboSK don't work on 1.13.2

### ISSUE THREAD

**Issue by ChifuyuKR** [TlatoaniHJ/MundoSK#30]
### Bug Report

Skript Version:

MundoSK Version: 1.8.5

Minecraft Version: 1.13.2

### Steps to Reproduce the Issue
Just install MundoSK

### Full Code

No code

### Errors on Reload (if applicable)

Same Error of console 
### Console Errors (if applicable)
[13:16:54 INFO]: [MundoSK] Enabling MundoSK v1.8.5*
[13:16:54 INFO]: [MundoSK] No worlds were assigned to load automatically
[13:16:54 INFO]: [MundoSK] Pie is awesome :D
[13:16:54 ERROR]: Error occurred while enabling MundoSK v1.8.5 (Is it up to date?)
java.lang.NoSuchMethodError: ch.njol.skript.lang.SyntaxElementInfo.<init>([Ljava/lang/String;Ljava/lang/Class;)V
at com.pie.tlatoani.Registration.ModifiableSyntaxElementInfo$Effect.<init>(ModifiableSyntaxElementInfo.java:57) ~[?:?]
at com.pie.tlatoani.ListUtil.ListUtil.load(ListUtil.java:41) ~[?:?]
at com.pie.tlatoani.Registration.Registration.register(Registration.java:29) ~[?:?]
at com.pie.tlatoani.Mundo.onEnable(Mundo.java:80) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-525]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-525]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-525]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-525]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-525]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-525]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-525]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-525]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-525]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-525]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[13:16:54 INFO]: [MundoSK] Disabling MundoSK v1.8.5
[13:16:54 INFO]: [MundoSK] Closed all function sockets (if any were open)
[13:16:54 INFO]: [MundoSK] Stopped all WebSocket servers (if any were open)
[13:16:54 INFO]: [MundoSK] Successfully saved all (if any) world loaders

### Other Useful Info (ex. addons and plugins you are using)
![image](https://user-images.githubusercontent.com/43295611/59852253-bee6e780-936e-11e9-8a07-dfc772e3c791.png)
